AgentPortal.Web/Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AgentPortal.Models;
using AgentPortal.Repositories;
using AgentPortal.Repositories.StoredProcedures;
using AgentPortal.Services;
using AgentPortal.Support;
using AgentPortal.Support.Attributes;
using AgentPortal.Support.DataObjects;
using AgentPortal.Support.Enums;
using AgentPortal.Support.Integrations;
using AgentPortal.Support.Utilities;

//using DevExpress.Data.Filtering;
//using DevExpress.Xpo;
using log4net;
using PalmInsure.Palms.Utilities;

namespace AgentPortal.Controllers
{
    public class QuoteController : BaseController
    {
        private readonly QuoteService QuoteService;

        public ReportService ReportService;

        #region Creation

        private List<string> listPDFs = new List<string>();
        private List<string> listParamNames = new List<string>();
        private List<string> listParamValues = new List<string>();
        private string reportName = null;
        private readonly ILog quoteControllerLog = LogManager.GetLogger("QuoteControllerLogger");

        public QuoteController(QuoteService quoteService, ReportService reportService)
        {
            QuoteService = quoteService;
            ReportService = reportService;
        }
        #region Helper Methods

        private string GetUserIP()
        {
            var ipList = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            if (!string.IsNullOrEmpty(ipList)) return ipList.Split(',')[0];

            return Request.ServerVariables["REMOTE_ADDR"];
        }

        public ActionResult Index()
        {
            return RedirectToAction("Create");
        }

        #endregion

        public ActionResult Create()
        {
            if (!PortalRightsUtils.HasRights("QUOTE EDIT", Sessions.Instance.AgentCode, true))
                return RedirectToAction("Search", "Agent");

            if (AgentUtils.GetScalar<bool>("IsRequireCall", Sessions.Instance.AgentCode))
                return RedirectToAction("PleaseCall", "Agent");

            var model = QuoteService.CreateQuote(); // IQuoteService later on

            Sessions.Instance.PrevAction = "CREATE";
            TempData["DriverId"] = "";
            TempData["VehicleId"] = "";
            LogUtils.Log(Sessions.Instance.Username, string.Format("Created Quote {0}".ToUpper(), model.QuoteId),
                "DEBUG");
            return RedirectToAction("Edit", new {id = Blowfish.Encrypt_CBC(model.QuoteId)});
        }

        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Search", "Agent");
            if (string.IsNullOrEmpty(Sessions.Instance.AgentCode)) return RedirectToAction("Login", "Agent");
            /*
				[NOTE] Quote Edit View
				---------------------------- 
				Top portaion of the edit controller is used for briding from Quickaja Quote and Accu Auto.
				It will do any relevant checks against PolicyQuote and Agents tables to decide if the agent
				has proper credentials to auto login and go straight to the edit quote. 
			  
				If something does not match, agent is dumped to the login screen where they can login and search for what they need.
			*/

            try
            {
                id = Blowfish.Decrypt_CBC(id);
            }
            catch
            {
                //return RedirectToAction("Search", "Agent");  //LF 5/1/19
            }

            Sessions.Instance.PolicyNo = id;
            if (string.IsNullOrEmpty(Sessions.Instance.AgentCode)) //LF ???
            {
                //init vars
                string agentPass;
                IAgents getAgentData;
                using (var uow = UnitOfWorkFactory.GetUnitOfWork())
                {
                    //----------------
                    var getQuoteData = uow.QuoteRepository.GetQuote(id);
                    if (getQuoteData == null) return RedirectToAction("Search", "Agent");

                    var raterType = getQuoteData.FromRater;
                    var agentEmailAddr = getQuoteData.AgentAccount.Trim();
                    Sessions.Instance.EmailAddress = agentEmailAddr;
                    var quotePass = string.IsNullOrEmpty(getQuoteData.AgentPassword)
                        ? ""
                        : Blowfish.Decrypt_CBC(getQuoteData.AgentPassword);
                    //----------------
                    //Getr agents password/info based on incoming rater type
                    if (raterType == "AA")
                    {
                        getAgentData = uow.AgentRepository.GetAgentByAlternateEmail(agentEmailAddr);

                        if (getAgentData != null)
                        {
                            agentPass = string.IsNullOrEmpty(getAgentData.AltPassword)
                                ? ""
                                : Blowfish.Decrypt_CBC(getAgentData.AltPassword);
                            Sessions.Instance.AgentCode = getAgentData.AgentCode;
                            Sessions.Instance.IsAuth = true;
                            Sessions.Instance.IsAgent = true;
                        }
                        else
                        {
                            return RedirectToAction("Login", "Agent");
                        }
                    }
                    else
                    {
                        getAgentData = uow.AgentRepository.GetAgentByEmail(agentEmailAddr);

                        if (getAgentData != null)
                        {
                            agentPass = string.IsNullOrEmpty(getAgentData.Password)
                                ? ""
                                : Blowfish.Decrypt_CBC(getAgentData.Password);
                            Sessions.Instance.AgentCode = getAgentData.AgentCode;
                            Sessions.Instance.IsAuth = true;
                            Sessions.Instance.IsAgent = true;
                        }
                        else
                        {
                            return RedirectToAction("Login", "Agent");
                        }
                    }

                    //----------------
                    if (agentPass != quotePass) return RedirectToAction("Login", "Agent");
                    var updateQuote = uow.QuoteRepository.GetQuote(Sessions.Instance.PolicyNo);
                    updateQuote.Bridged = !string.IsNullOrEmpty(raterType);
                    updateQuote.AgentCode = Sessions.Instance.AgentCode;
                    uow.QuoteRepository.SaveQuote(updateQuote);
                    uow.PolicyRepository.SavePolicyPreference(Sessions.Instance.PolicyNo, "Preferred_Language", "ENGLISH");
                    uow.Save();

                    //----------------
                    LogUtils.Log(agentEmailAddr, GetUserIP());

                    LogUtils.Log(Sessions.Instance.Username,
                        string.Format("Bridged from {0} for Quote {1}".ToUpper(), raterType,
                            Sessions.Instance.PolicyNo),
                        "DEBUG");
                }
            } //END Pre-Quote Edit briding to see if agent is able to auto login

            //------------------------------------------------------------------------------
            if (!PortalRightsUtils.HasRights("QUOTE EDIT", Sessions.Instance.AgentCode, true))
                return RedirectToAction("Search", "Agent");

            //------------------------------------------------------------------------------
            Sessions.Instance.IsNewQuote = Sessions.Instance.PrevAction == "CREATE" ? true : false;
            using (var uow = UnitOfWorkFactory.GetUnitOfWork())
            {

                var preferenceForQuote = uow.PolicyRepository.GetPolicyPreference(Sessions.Instance.PolicyNo, "Preferred_Language");
                string languagePreference;
                if (preferenceForQuote == null)
                {
                    languagePreference = "ENGLISH";
                    uow.PolicyRepository.SavePolicyPreference(Sessions.Instance.PolicyNo,"Preferred_Language",languagePreference);
                    uow.Save();
                }
                else
                {
                    languagePreference = preferenceForQuote.Value;
                }

                var compDed = "NONE";
                var collDed = "NONE";
                id = string.IsNullOrEmpty(id) ? Sessions.Instance.PolicyNo : id;
                var quote = uow.QuoteRepository.GetQuote(id);
                //----------------------
                if (quote == null)
                {
                    LogUtils.Log(Sessions.Instance.Username, string.Format("Quote Not Found: {0}".ToUpper(), id),
                        "FATAL");
                    return RedirectToAction("Search", "Agent", new {id = "Q404"});
                }

                var model = QuoteService.CreateQuoteCars(quote as XpoPolicyQuote, languagePreference, compDed, collDed, id);

                /*     else
                     {
                         if (model.WorkLossGroup == 1 || model.WorkLossGroup == 2)
                             model.Workloss = true;
                         else
                             model.Workloss = false;
                     }  */
                //LF 4/1/19 shouldn't be here            if (model.Workloss == false)
                //                model.WorkLossGroup = 2; // 3;
                //----------------------
                Sessions.Instance.PrevAction = "EDIT";
                LogUtils.Log(Sessions.Instance.Username,
                    string.Format("Edit Quote {0}".ToUpper(), Sessions.Instance.PolicyNo), "INFO");
                TempData["QuoteModel"] = model;
                TempData["DriverId"] = "";
                TempData["VehicleId"] = "";

AgentPortal.Web/Views/Quote/EditorTemplates/AddressModel.cshtml
@model AgentPortal.Models.AddressModel

<tr>
    <td>Street</td>
    <td>
        @Html.TextBoxFor(m => m.StreetAddress, new { @class = "textEdit" })
        @Html.ValidationMessageFor(m => m.StreetAddress)
    </td>
</tr>
<tr>
    <td>City/State/ZIP</td>
    <td>
        @Html.DropDownListFor(m => m.City, new[] {
            new SelectListItem() { Text = "Find by Zip" }
        }, new { disabled = "disabled", @class="textEdit" })
        @*@Html.TextBoxFor(m => m.City, new { @class = "txtEdit27", disabled = "disabled" })*@
        @Html.TextBoxFor(m => m.State, new { size = 2, @class = "txtEdit27", disabled = "disabled" })
        @Html.TextBoxFor(m => m.ZIPCode, new { size = 6, @class = "txtEdit27 zipcode" })
        @Html.ValidationMessageFor(m => m.City)
        @Html.ValidationMessageFor(m => m.State)
        @Html.ValidationMessageFor(m => m.ZIPCode)
    </td>
</tr>

AgentPortal.Web/Views/Quote/EditorTemplates/DateTime.cshtml
@model DateTime?
           
@{
    string shortDate = Model.HasValue ? Model.Value.ToShortDateString() : "";
}

@*@Html.TextBoxFor(m => m, new { @class = "datepicker", Value = shortDate })*@
@Html.TextBoxFor(m => m, new { @class = "textEdit", Value = shortDate })

AgentPortal.Web/Views/Quote/EditorTemplates/Driver.cshtml
@using AgentPortal.Support
@using PalmInsure

@model AgentPortal.Models.DriverModel

@{
    ViewData.TemplateInfo.HtmlFieldPrefix = "";

    SelectListItem[] states = StaticData.USAStates
        .Select(m => new SelectListItem()
        {
            Text = m.Value,
            Value = m.Key,
            Selected = m.Key == "FL"
        }).ToArray();


    SelectListItem[] GenderList = new[] {
        new SelectListItem() { Text = "SELECT" },
        new SelectListItem() { Text="MALE" },
        new SelectListItem() { Text="FEMALE" }
    };


    SelectListItem[] RelationList = new[] {
        new SelectListItem() { Text = "INSURED" },
        new SelectListItem() { Text="CHILD" },
        new SelectListItem() { Text="BROTHER/SISTER" },
        new SelectListItem() { Text="PARENT" },
        new SelectListItem() { Text="SELF" },
        new SelectListItem() { Text="SPOUSE" },
        new SelectListItem() { Text="SON" },
        new SelectListItem() { Text="DAUGHTER" },
        new SelectListItem() { Text="OTHER" },
        new SelectListItem() { Text="NONRELATIVE" }
    };
}

@Html.HiddenFor(m => m.QuoteId)
@Html.HiddenFor(m => m.DriverId)

@using (Html.BeginForm("DriverAdd", "Quote", new AjaxOptions()
{
    OnSuccess = "onDriverAddSuccess",
    OnFailure = "onDriverAddFailure",
    UpdateTargetId = "DriversTable"
}))
{
@Html.HiddenFor(m => m.IsEdit)    
@Html.HiddenFor(m => m.DriverIndex)
@Html.HiddenFor(m => m.OldDlNum)

 <script type="text/javascript">
     if ($("#Relation").length > 0) {

         $("#Relation").trigger("change");
         $("#Relation").live('change', function () 
         {
             if ($("#Relation option:selected").text() == "INSURED") 
            {
                $("#IsExcluded").attr("checked", null);
                $("#IsExcluded").attr("disabled", "disabled");
            }
            else 
            {
                 $("#IsExcluded").attr("disabled", null);
             }
         });
    }
     ///////////////////////////////////////////////////////
     $("#DateOfBirth").live("blur", function () {
        $.getJSON("@Url.Action("ValidateDate", "AjaxHelpers")", {
			date: $("#DateOfBirth").val()
		}, function (data) {
			if(data.returnMsg == "SUCCESS")
			{
                $("#DateOfBirth").val(data.returnDate);
			}
		});
    });

    $(document).ready(function(){
        @**************************************************@
        $("#OldDlNum").val($("#DriversLicense").val());
        @**************************************************@
        $("#IsExcluded").live("click", function() {
            if ($(this).attr("checked")) {
                $("#DriversLicense").val("UNLICENSED");
                $('#DateLicensed').attr('disabled', 'disabled');
            } else {
                $("#DriversLicense").val("");
                $('#DateLicensed').attr('disabled', null);
            }
        });
        @**************************************************@
    });
</script>  
    <div id="driverErrMsg"></div>
<table class="tbl100">
    <tr>
        <th colspan="5">Personal Information</th>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.FirstName)</td>
        <td>
            @Html.TextBoxFor(m => m.FirstName, new { @class = "textEdit", @tabindex = "1" })
            @Html.ValidationMessageFor(m => m.FirstName)
        </td>


        <td>@Html.LabelFor(m => m.DateOfBirth)</td>
        <td>
            @Html.TextBoxFor(m => m.DateOfBirth, new { @class = "textEdit", @tabindex = "5" })
            @Html.ValidationMessageFor(m => m.DateOfBirth)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.MiddleInitial)</td>
        <td>
            @Html.TextBoxFor(m => m.MiddleInitial, new { @size = "1", @class = "textEdit", @maxlength = "1", @tabindex = "2" })
            @Html.ValidationMessageFor(m => m.MiddleInitial)
        </td>
        <td>@Html.LabelFor(m => m.Gender)</td>
        <td>
           @* @Html.DropDownListForEnum(m => m.Gender)    
           *@
            @Html.DropDownListFor(m => m.Gender, GenderList, new { @class = "textEdit", @tabindex = "6" })
            @Html.ValidationMessageFor(m => m.Gender)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.LastName)</td>
        <td>
            @Html.TextBoxFor(m => m.LastName, new { @class = "textEdit", @tabindex = "3" })
            @Html.ValidationMessageFor(m => m.LastName)
        </td>

        <td>    @Html.LabelFor(m => m.IsMarried)</td>
        <td>
            @Html.CheckBoxFor(m => m.IsMarried, new { @tabindex = "7" })
            @Html.ValidationMessageFor(m => m.IsMarried)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.Suffix)</td>
        <td>
            @Html.TextBoxFor(m => m.Suffix, new { @class = "textEdit", @tabindex = "4" })
            @Html.ValidationMessageFor(m => m.Suffix)
        </td>

        <td>@Html.LabelFor(m => m.Relation)</td>
        <td>
                @*@Html.DropDownListForEnum(m => m.Relation)*@
            @Html.DropDownListFor(m => m.Relation, RelationList, new { @class = "textEdit", @tabindex = "8" })
            @Html.ValidationMessageFor(m => m.Relation)
        </td>
    </tr>
    <tr>
        <td colspan="2">
        
        </td>
        <td>
            @Html.LabelFor(m => m.IsExcluded)
        </td>
        <td>
            @Html.CheckBoxFor(m => m.IsExcluded, new { disabled = "disabled", @tabindex = "9" })
        </td>
    </tr>
</table>
<table class="tbl100" style="float:left;">
    <tr>
        <th colspan="4">License Information</th>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.IsInternationalLicense)</td>
        <td>@Html.CheckBoxFor(m => m.IsInternationalLicense, new { @tabindex = "10" })</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.HasSeniorDefDrvDisc)
        </td>
        <td>
            @Html.CheckBoxFor(m => m.HasSeniorDefDrvDisc, new { @tabindex = "11" })
        </td>
        <td>
            @Html.LabelFor(m => m.SeniorDefDrvDate)
        </td>
        <td>
            @Html.TextBoxFor(m => m.SeniorDefDrvDate, new { @class = "textEdit", @tabindex = "12", @disabled = "disabled" })
            @Html.ValidationMessageFor(m => m.SeniorDefDrvDate)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.HasSR22)
        </td>
        <td>
            @Html.CheckBoxFor(m => m.HasSR22, new { @tabindex = "13", @disabled = "disabled", @class="disabled" })
        </td>
         <td>
            @Html.LabelFor(m => m.SR22CaseNo)
        </td>
        <td>
            @Html.TextBoxFor(m => m.SR22CaseNo, new { @class = "textEdit disabled", @tabindex = "14", @disabled = "disabled" })
            @Html.ValidationMessageFor(m => m.SR22CaseNo)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.DriversLicense)</td>
        <td>
            @Html.TextBoxFor(m => m.DriversLicense, new { @class = "textEdit", @tabindex = "15", @maxlength="20" })
        </td>
        <td>@Html.LabelFor(m => m.LicenseState)</td>
        <td>
            @Html.DropDownListFor(m => m.LicenseState, states, new { @class = "textEdit", @tabindex = "16" })
        </td>
    </tr>
    <tr class="validationRow">
        <td colspan="4">
            @Html.ValidationMessageFor(m => m.DriversLicense)
            @Html.ValidationMessageFor(m => m.LicenseState)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.Unverifiable)</td>
        <td>@Html.CheckBoxFor(m => m.Unverifiable, new { @tabindex = "10", @disabled = "disabled" })</td>
        <td>@Html.LabelFor(m => m.DateLicensed)</td>
        <td>
            @Html.TextBoxFor(m => m.DateLicensed, new { @class = "date textEdit validateDate", @tabindex = "17" })
            @Html.ValidationMessageFor(m => m.DateLicensed)
        </td>
    </tr>
</table>
    
<table class="tbl49" style="float:left;">
    <tr>
        <th colspan="2">Employer Information</th>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.EmployerName)</td>
        <td>
            @Html.TextBoxFor(m => m.EmployerName, new { @class = "textEdit", @tabindex = "18" })
            @Html.ValidationMessageFor(m => m.EmployerName)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.Occupation)</td>
        <td>
            @Html.TextBoxFor(m => m.Occupation, new { @class = "textEdit", @tabindex = "19" })
        </td>
    </tr>
</table>
<div class="clear"></div>

@Html.DisplayFor(m => m.Violations)
 
<div class="clear"></div>
<input class="btnSubmit" type="submit" tabindex="20" value="@(Model == null ? "Save Driver" : "Save Driver")" id="btnAddDriver" />
    
}

AgentPortal.Web/Views/Quote/EditorTemplates/InsuredModel.cshtml
@model AgentPortal.Models.InsuredModel

    <td>@Html.TextBoxFor(m => m.FirstName, new { size = "5", @class="textEdit" })</td>
    <td>@Html.TextBoxFor(m => m.MiddleInitial, new { size = "1", @class = "txtEdit65" })</td>
    <td>@Html.TextBoxFor(m => m.LastName, new { @class = "textEdit" })</td>
    <td>@Html.TextBoxFor(m => m.Suffix, new { size = "6", @class = "txtEdit80" })</td>
</tr>
<tr>
    <td colspan="5" class="insuredValidationRow">
        @Html.ValidationMessageFor(m => m.FirstName)
        @Html.ValidationMessageFor(m => m.LastName)
        @Html.ValidationMessageFor(m => m.MiddleInitial)
        @Html.ValidationMessageFor(m => m.Suffix)
    </td>

AgentPortal.Web/Views/Quote/EditorTemplates/Vehicle.cshtml
@using PalmInsure;

@model AgentPortal.Models.VehicleModel

@{
    SelectListItem[] makes = new [] {
        new SelectListItem() {
            Text = Model != null && Model.Make != null
                ? Model.Make
                : "Enter Year",
            Selected = true
        }
    };
    SelectListItem[] models = new[] {
        new SelectListItem() {
            Text = Model != null && Model.VehModel != null
                ? Model.VehModel
                : "Select Make",
            Selected = true
        }
    };
    SelectListItem[] bodyStyles = new[] {
        new SelectListItem() {
            Text = Model != null && Model.Style != null
                ? Model.Style
                : "Select Model",
            Selected = true
        }
    };
    
    
    ViewData.TemplateInfo.HtmlFieldPrefix = "";
}

@Html.HiddenFor(m => m.QuoteId)
@Html.HiddenFor(m => m.VehicleId)

@using (Html.BeginForm("VehicleAdd", "Quote", new AjaxOptions()
{
    OnSuccess = "onVehicleAddSuccess",
    OnFailure = "onVehicleAddFailure",
    UpdateTargetId = "VehiclesTable"
}))
{
@Html.HiddenFor(m => m.IsEdit)    
@Html.HiddenFor(m => m.CarIndex)
@Html.HiddenFor(m => m.CompSymbol)
<div id="vinErrorMsg"></div>
<table class="tbl100">
    <tr>
        <th colspan="8">Vehicle Information</th>
    </tr>

    <tr>
        <td>
            @Html.LabelFor(model => model.Year)
        </td>
        <td style="width: 12%;">
            @Html.TextBoxFor(model => model.Year, new { @class = "textEdit", @tabindex = "2" })
            @Html.ValidationMessageFor(model => model.Year)
        </td>
        <td style="width: 15px;">
            @Html.LabelFor(model => model.Make)
        </td>
        <td>
            @Html.DropDownListFor(model => model.Make, makes, new { @class = "txtEditAlt", disabled = "disabled", @tabindex = "3" })
        </td>
        <td style="width: 75px;">
            @Html.LabelFor(model => model.VehModel)
        </td>
        <td>
            @Html.DropDownListFor(model => model.VehModel, models, new { @class = "txtEditAlt", disabled = "disabled", @tabindex = "4" })
        </td>
        <td>
            @Html.LabelFor(model => model.Style)
        </td>
        <td>
            @Html.DropDownListFor(model => model.Style, bodyStyles, new { @class = "txtEditAlt", disabled = "disabled", @tabindex = "5" })
        </td>
    </tr>

    <tr>
        <td>
            @Html.LabelFor(model => model.VIN)
        </td>
        <td colspan="7">        
            @Html.TextBoxFor(model => model.VIN, new { @class = "txtEdit99", @tabindex = "1", @maxlength = "20" })
            @Html.ValidationMessageFor(model => model.VIN)
        </td>
    </tr>
    <tr>
        <td  colspan="9">
            <div class="phydamChkbx textAlignCenter">
                <span>@Html.LabelFor(model => model.HasPhyDam)?</span>
                <span><label>Yes</label></span>@Html.RadioButtonFor(m => m.HasPhyDam, true, new { @tabindex = "6" })
                <span><label>No</label></span>@Html.RadioButtonFor(m => m.HasPhyDam, false, new { @tabindex = "6" })
                @Html.ValidationMessageFor(model => model.HasPhyDam)
            </div>
        </td>
    </tr>
    <tr>
        <td></td>
        <td colspan="2">
            @Html.CheckBoxFor(model => model.HasAntiLockBrakes, new { @tabindex = "7" })
            @Html.LabelFor(model => model.HasAntiLockBrakes)     
        </td>
        <td>
            @Html.CheckBoxFor(model => model.IsPurchasedNew, new { @tabindex = "8" })
            @Html.LabelFor(model => model.IsPurchasedNew)
        </td>
        <td colspan="2">
        </td>
        <td colspan="2">
        </td>
    </tr>
        
    <tr>
        <td></td>
        <td colspan="2">
            @Html.CheckBoxFor(model => model.HasAirbag, new { @tabindex = "9" })
            @Html.LabelFor(model => model.HasAirbag)
        </td>
        <td>
            @Html.CheckBoxFor(model => model.IsBusinessUse, new { @tabindex = "10" })
            @Html.LabelFor(model => model.IsBusinessUse)
        </td>
         <td>
            @Html.LabelFor(model => model.MilesToWork)
        </td>
        <td>
            @Html.TextBoxFor(model => model.MilesToWork, new { @class = "textEdit", @tabindex = "11" })
        </td>
        <td colspan="2"></td>
    </tr>

    <tr>
        <td></td>
        <td colspan="2">
            @Html.CheckBoxFor(model => model.HasAntiTheftDevice, new { @tabindex = "12" })
            @Html.LabelFor(model => model.HasAntiTheftDevice)
        </td>
        <td>
            @Html.CheckBoxFor(model => model.Artisan, new { @tabindex = "12" })
            @Html.LabelFor(model => model.Artisan)
        </td>
        <td>
            @Html.LabelFor(model => model.AmountCustom)
        </td>
        <td>
            @Html.TextBoxFor(model => model.AmountCustom, new { @class = "textEdit" })
        </td>
        <td colspan="2"></td>
    </tr>

    <tr>
        <td></td>
        <td colspan="2">
            @Html.CheckBoxFor(model => model.HasConvOrTT, new { @tabindex = "13" })
            @Html.LabelFor(model => model.HasConvOrTT)  
        </td>
        <td>
            @Html.CheckBoxFor(model => model.MoreThan10MilesToWk, new { @tabindex = "14" })
            @Html.LabelFor(model => model.MoreThan10MilesToWk)
        </td>
        <td colspan="4"></td>
    </tr>

</table>

@Html.DisplayFor(m => m.LienHolders)
    
<input id="btnAddVehicle" class="btnSubmit" tabindex="15" type="submit" value="@(Model == null ? "Save Vehicle" : "Save Vehicle")" />
}

<script type="text/javascript">
    $(document).ready(function() {
        if ($("#VIN").val() != "") {
            if ($("#VIN").val().length != 17) {
                $("#VIN").trigger("blur");
            }
            else {
                $("#Make").attr('disabled', null);
                $("#VehModel").attr('disabled', null);
                $("#Style").attr('disabled', null);
            }
        }
    });
</script>

AgentPortal.Web/Views/Quote/EditorTemplates/ViolationAddModel.cshtml
@using PalmInsure;

@model AgentPortal.Models.ViolationAddModel

@{
    ViewData.TemplateInfo.HtmlFieldPrefix = "";
    
    SelectListItem[] ViolationsDropDown = new[] {
        new SelectListItem() { Text = "SELECT"}
    };
}

@Html.HiddenFor(m => m.DriverId)
@Html.HiddenFor(m => m.DriverIndex)
<table class="tbl100 ViolationTable">
    <tr>
        <td>@Html.LabelFor(m => m.Description)</td>
        <td>
            @Html.DropDownListFor(m => m.Description, ViolationsDropDown)
            @Html.ValidationMessageFor(m => m.Description)
        </td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.Date)</td>
        <td>
            @Html.EditorFor(m => m.Date)
            <br />
            <span class="date-field-custom-validation" style="font-size:small;"></span>
        </td>
    </tr>

</table>

<input class="btnSubmit"  type="submit" id="addDriverViolationBtnSubmit" value="Add Driver Violation" />